const users = [
    {nama: 'Nur Fadilah', umur: 22, alamat: 'Jl. Melati 1', email: 'nur.fadilah@mail.com'},
    {nama: 'Arizal Muhamad Ridwan', umur: 24, alamat: 'Jl. Kenanga 2', email: 'arizal.ridwan@mail.com'},
    {nama: 'Daffa Hafiz Alfianto', umur: 21, alamat: 'Jl. Mawar 3', email: 'daffa.hafiz@mail.com'},
    {nama: 'Firenze Higa Putra', umur: 23, alamat: 'Jl. Anggrek 4', email: 'firenze.putra@mail.com'},
    {nama: 'Ihsan Ahmad Al-Ghifari', umur: 25, alamat: 'Jl. Flamboyan 5', email: 'ihsan.ghifari@mail.com'},
    {nama: 'Miftah Adz Dzaudan Islam', umur: 20, alamat: 'Jl. Dahlia 6', email: 'miftah.islam@mail.com'},
    {nama: 'Nur Hasanah', umur: 23, alamat: 'Jl. Cempaka 7', email: 'nur.hasanah@mail.com'},
    {nama: "Siti Sa'Diyah", umur: 22, alamat: 'Jl. Teratai 8', email: 'siti.sadiyah@mail.com'},
    {nama: 'Muhamad Sayyid Fadhil', umur: 26, alamat: 'Jl. Kamboja 9', email: 'sayyid.fadhil@mail.com'},
    {nama: 'Jayas Permana', umur: 21, alamat: 'Jl. Sakura 10', email: 'jayas.permana@mail.com'},
    {nama: 'Raehan Nurmishuari', umur: 24, alamat: 'Jl. Melati 11', email: 'raehan.nurmishuari@mail.com'},
    {nama: 'Dwi Mutia Afifah', umur: 22, alamat: 'Jl. Kenanga 12', email: 'dwi.afifah@mail.com'},
    {nama: 'Alif Surya Pratama', umur: 23, alamat: 'Jl. Mawar 13', email: 'alif.pratama@mail.com'},
    {nama: 'Muhammad Rafli Putra Perdana', umur: 25, alamat: 'Jl. Anggrek 14', email: 'rafli.perdana@mail.com'},
    {nama: 'Adi Kurniawan', umur: 22, alamat: 'Jl. Flamboyan 15', email: 'adi.kurniawan@mail.com'},
    {nama: 'Muhammad Randya Kurniawan', umur: 21, alamat: 'Jl. Dahlia 16', email: 'randya.kurniawan@mail.com'},
    {nama: 'Muhammad Syawal Arif Billah', umur: 24, alamat: 'Jl. Cempaka 17', email: 'syawal.billah@mail.com'},
    {nama: 'Sabrina Marliani', umur: 23, alamat: 'Jl. Teratai 18', email: 'sabrina.marliani@mail.com'},
    {nama: 'Muhammad Khalid Shafwan I', umur: 22, alamat: 'Jl. Kamboja 19', email: 'khalid.shafwan@mail.com'},
    {nama: 'Muhammad Yanwar', umur: 25, alamat: 'Jl. Sakura 20', email: 'yanwar@mail.com'},
    {nama: 'Mufadhal', umur: 23, alamat: 'Jl. Melati 21', email: 'mufadhal@mail.com'},
    {nama: 'Lutfi Fuat Azhar', umur: 22, alamat: 'Jl. Kenanga 22', email: 'lutfi.azhar@mail.com'},
    {nama: 'Tegar Asayahanda Firdaus', umur: 24, alamat: 'Jl. Mawar 23', email: 'tegar.firdaus@mail.com'},
    {nama: 'Rizaldy Rafa Akhmad', umur: 21, alamat: 'Jl. Anggrek 24', email: 'rizaldy.akhmad@mail.com'},
    {nama: 'Sakha As Shidqi', umur: 23, alamat: 'Jl. Flamboyan 25', email: 'sakha.shidqi@mail.com'},
    {nama: 'Syahrul Mubaroq', umur: 22, alamat: 'Jl. Dahlia 26', email: 'syahrul.mubaroq@mail.com'},
    {nama: 'Aditya Febriadi', umur: 25, alamat: 'Jl. Cempaka 27', email: 'aditya.febriadi@mail.com'},
    {nama: 'Rifa Fradita Safara', umur: 23, alamat: 'Jl. Teratai 28', email: 'rifa.safara@mail.com'},
    {nama: 'Irham Syahputra', umur: 22, alamat: 'Jl. Kamboja 29', email: 'irham.syahputra@mail.com'},
    {nama: 'Muhammad Andhika Thata', umur: 24, alamat: 'Jl. Sakura 30', email: 'andhika.thata@mail.com'},
    {nama: 'Yasser Fajar Purwawiwaha', umur: 21, alamat: 'Jl. Melati 31', email: 'yasser.purwawiwaha@mail.com'},
    {nama: 'Wahyu Andrianto Wibowo', umur: 23, alamat: 'Jl. Kenanga 32', email: 'wahyu.wibowo@mail.com'},
    {nama: 'Amelia Ardhana Riswadi', umur: 22, alamat: 'Jl. Mawar 33', email: 'amelia.riswadi@mail.com'},
    {nama: 'Muhammad Alhaqi', umur: 25, alamat: 'Jl. Anggrek 34', email: 'alhaqi@mail.com'},
    {nama: 'Achmad Zaki Al Akbar', umur: 23, alamat: 'Jl. Flamboyan 35', email: 'zaki.alakbar@mail.com'},
    {nama: 'Bagas Adi Anugerah', umur: 22, alamat: 'Jl. Dahlia 36', email: 'bagas.anugerah@mail.com'},
    {nama: 'Maulana Izuddin Audadi Icham', umur: 24, alamat: 'Jl. Cempaka 37', email: 'maulana.icham@mail.com'},
    {nama: 'Al Hadid Aditya Abidin', umur: 21, alamat: 'Jl. Teratai 38', email: 'alhadid.abidin@mail.com'},
    {nama: 'Muhamad Rizki Ramadhan Siregar', umur: 23, alamat: 'Jl. Kamboja 39', email: 'rizki.siregar@mail.com'},
    {nama: 'Sahlaa Nurrahmah', umur: 22, alamat: 'Jl. Sakura 40', email: 'sahlaa.nurrahmah@mail.com'},
    {nama: 'Villian Shah Akwa', umur: 25, alamat: 'Jl. Melati 41', email: 'villian.akwa@mail.com'},
    {nama: 'Didik Hariyadi', umur: 23, alamat: 'Jl. Kenanga 42', email: 'didik.hariyadi@mail.com'},
    {nama: 'Safira Paramita Mustamsir', umur: 22, alamat: 'Jl. Mawar 43', email: 'safira.mustamsir@mail.com'},
    {nama: 'Yusta Erlangga', umur: 24, alamat: 'Jl. Anggrek 44', email: 'yusta.erlangga@mail.com'},
    {nama: 'Muhammad Ezah Septiyan', umur: 21, alamat: 'Jl. Flamboyan 45', email: 'ezah.septiyan@mail.com'},
    {nama: 'Achmad Ario Bintang Farizi', umur: 23, alamat: 'Jl. Dahlia 46', email: 'ario.farizi@mail.com'},
    {nama: 'Muhammad Nazwaly Sukrisna', umur: 22, alamat: 'Jl. Cempaka 47', email: 'nazwaly.sukrisna@mail.com'},
    {nama: 'Dhimas Ananda Ruswanto Putra', umur: 25, alamat: 'Jl. Teratai 48', email: 'dhimas.putra@mail.com'},
    {nama: 'Bagas Firdaus Tri Putra', umur: 23, alamat: 'Jl. Kamboja 49', email: 'bagas.triputra@mail.com'},
    {nama: 'Muhammad Arifin Ilham', umur: 22, alamat: 'Jl. Sakura 50', email: 'arifin.ilham@mail.com'},
    {nama: 'Umar Mukhtar', umur: 24, alamat: 'Jl. Melati 51', email: 'umar.mukhtar@mail.com'},
    {nama: 'Restu Cipta Hadi Kusuma', umur: 21, alamat: 'Jl. Kenanga 52', email: 'restu.kusuma@mail.com'},
    {nama: 'Muhammad Nur Izzuddin', umur: 23, alamat: 'Jl. Mawar 53', email: 'nur.izzuddin@mail.com'},
    {nama: 'Ahmad Sahrija', umur: 22, alamat: 'Jl. Anggrek 54', email: 'ahmad.sahrija@mail.com'},
    {nama: 'Fahmi Affandy Rizzan', umur: 25, alamat: 'Jl. Flamboyan 55', email: 'fahmi.rizzan@mail.com'},
];

export default users;
